xxx

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,58 +4,43 @@ version: 2.1
 
 setup: true
 
-orbs:
-  file-changes:
-    commands:
-      halt-if-not-changed:
-        parameters:
-          pattern:
-            type: string
-            description: "Pattern to match the changed files."
-          diff-filter:
-            type: string
-            default: "d"
-            description: "Filter files by status. See: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRT"
-          base-branch:
-            type: string
-            description: "Halt the job if the specified files are not changed."
-        steps:
-          - checkout
-          - run:
-              name: "Check if files are changed"
-              command: |
-                echo "Fetching base branch..."
-                BASE_BRANCH=$(git ls-remote --symref origin HEAD | grep -oP '(?<=refs/heads/)\S+')
-                BASE_SHA1=$(git ls-remote --symref origin HEAD | tail -n 1 | cut -f 1)
-                echo "Base SHA1: $BASE_SHA1"
-                echo "Base BRANCH: $BASE_BRANCH"
-                echo "BASE BRANCH FROM PARAM: << parameters.base-branch >>"
-                echo
-
-                # Since the difference of files is calculated based on the default branch,
-                # the difference cannot be obtained if the PR is created from the default branch.
-                if [ $BASE_BRANCH = $CIRCLE_BRANCH ]; then
-                  echo "Base branch is same as default branch. Regular job will be executed."
-                  exit 0
-                fi
-
-                echo "Changed files:"
-                git diff --name-only --diff-filter=<< parameters.diff-filter >> $BASE_SHA1...$CIRCLE_SHA1 | tee changed.txt
-                echo
-                if [ $? -ne 0 ]; then
-                  echo "Failed to get changed files. Regular job will be executed."
-                  exit 0
-                fi
-
-                echo "Matched files:"
-                cat changed.txt | grep -P -e "<< parameters.pattern >>" | tee matched.txt || true
-                echo
-                if [ ! -s matched.txt ]; then
-                  echo "not matched. skip."
-                  circleci-agent step halt
-                fi
-
 commands:
+  halt-if-not-changed:
+    parameters:
+      pattern:
+        type: string
+        description: "Pattern to match the changed files."
+      diff-filter:
+        type: string
+        default: "d"
+        description: "Filter files by status. See: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRT"
+    steps:
+      - checkout
+      - run:
+          name: "Check if files are changed"
+          command: |
+            BASE_REVISION="<< pipeline.git.base_revision >>"
+            if [ -z "$BASE_REVISION" ]; then
+              # If base_revision is not specified, get the HEAD of origin
+              BASE_REVISION=$(git ls-remote --symref origin HEAD | tail -n 1 | cut -f 1)
+            fi
+            BUILD_REVISION=<"< pipeline.git.rebision >>""
+
+            echo "Changed files:"
+            git diff --name-only --diff-filter=<< parameters.diff-filter >> $BASE_REVISION...$BUILD_REVISION | tee changed.txt
+            echo
+            if [ $? -ne 0 ]; then
+              echo "Failed to get changed files. Regular job will be executed."
+              exit 0
+            fi
+
+            echo "Matched files:"
+            cat changed.txt | grep -P -e "<< parameters.pattern >>" | tee matched.txt || true
+            echo
+            if [ ! -s matched.txt ]; then
+              echo "not matched. skip."
+              circleci-agent step halt
+            fi
   skip-if-npm-dev-dependencies-update:
     description: "Job halted (irrelevant update: npm devDependencies)"
     steps:
@@ -92,9 +77,8 @@ jobs:
     # Add steps to the job
     # See: https://circleci.com/docs/configuration-reference/#steps
     steps:
-      - file-changes/halt-if-not-changed:
+      - halt-if-not-changed:
           pattern: "src/.*"
-          base-branch: << pipeline.git.base_revision >>
       - run:
           name: "Say hello"
           command: "echo Hello, World!"
