orbs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,35 +4,34 @@ version: 2.1
 
 setup: true
 
+orbs:
+  file-changes:
+    commands:
+      halt-if-not-changed:
+        parameters:
+          pattern:
+            type: string
+        steps:
+          - checkout
+          - run:
+              name: "Check if files are changed"
+              command: |
+                echo "Fetching base branch..."
+                BASE_SHA1=$(git ls-remote --symref origin HEAD | tail -n 1 | cut -f 1)
+
+                git diff --name-only $BASE_SHA1...$CIRCLE_SHA1 | tee /tmp/changed.txt
+                if [ $? -ne 0 ]; then
+                  echo "Failed to get changed files. Regular job will be executed."
+                  exit 0
+                fi
+
+                cat /tmp/changed.txt | grep -q -E "<< parameters.pattern >>" | tee matched.txt
+
+                if [ -s matched.txt ]; then
+                  echo "not matched. skip."
+                  circleci-agent step halt
+
 commands:
-  halt-if-not-changed:
-    parameters:
-      pattern:
-        type: string
-    steps:
-      - run:
-          name: "Check if files are changed"
-          command: |
-            git clone --no-checkout --filter=blob:none --sparse --depth=1 $CIRCLE_REPOSITORY_URL .
-
-            echo "Fetching changed files..."
-            echo "Branch: << pipeline.git.branch >>"
-            git fetch origin << pipeline.git.branch >>
-
-            echo "Fetching base branch..."
-            base=$(git ls-remote --symref origin HEAD | tail -n 1 | cut -f 1)
-
-            git diff --name-only $base...origin/<< pipeline.git.branch >> | tee /tmp/changed.txt
-            if [ $? -ne 0 ]; then
-              echo "Failed to get changed files. Regular job will be executed."
-              exit 0
-            fi
-
-            cat /tmp/changed.txt | grep -q -E "<< parameters.pattern >>" | tee matched.txt
-
-            if [ -s matched.txt ]; then
-              echo "not matched. skip."
-              circleci-agent step halt
   skip-if-npm-dev-dependencies-update:
     description: "Job halted (irrelevant update: npm devDependencies)"
     steps:
@@ -69,7 +68,7 @@ jobs:
     # Add steps to the job
     # See: https://circleci.com/docs/configuration-reference/#steps
     steps:
-      - halt-if-not-changed:
+      - file-changes/halt-if-not-changed:
           pattern: "src/.*"
       - run:
           name: "Say hello"
